#로그파일남기기
#schema-${platform}.sql 파일과 data-${platform}.sql 파일을 읽어 드려서 스키마및 데이터 생성
#파일명 예 : schema-postgresql.sql, data-postgresql.sql
#spring.datasource.platform=postgresql

oauth2:
  expired-period: 3600
  resource-id: hirit-server
  public-key: -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnWgDV8UTN/7A8LPDOWus
    XzclbS7BJ4097xruXv+/nVG2nuiGI0ssDRbiyl4OinB0EWXxYq6l3n9SbU48BkWF
    Xf3Kkcqq34hGkUVba9YACHWckjb63iZ96jbnkMmJ/Ux9VGmUHBry2uS7vLST18XX
    2tT9p3dw1/A7vdA3IYbzuLmB4vjWTEFN8XsFL6qNNVBQUlePP5uPMAXCQNWCiw8J
    JEk0bV+KEd/2K7SI9yCQu1wykN1z7z2AZf/AqatyPxoaOfWBs17O1JA3i+eAEEqW
    XHkUFBbPredgle7jXkQgJBLs7igNCL6DGi8nxogjdY7IF1a8temNwlXJWTBPT2eD
    mQIDAQAB
    -----END PUBLIC KEY-----

# profiles defulat : dev mode
logging:
  level:
    sso:
      mac:
        alcoholic: DEBUG
    org:
      springframework: INFO
      hibernate:
        type:
          descriptor:
            sql: trace
spring:
  output:
    ansi:
      enabled: always
--- # datasource
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

--- # JPA
Spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
--- # SERVER port
server:
  port: 8080

--- # thymeleaf
spring:
  thymeleaf:
    cache: false
#  mvc:
#    static-path-pattern: /static/**

--- # oAuth ID / pwd
client-id: hirit
client-secret: hiritpw

---
#profiles = prod
---
spring:
  profiles: prod
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/springboot
#    username: lake
#    password: zxasqw12
logging:
  level:
    sso:
      mac:
        alcoholic: INFO
    org:
      springframework: INFO
server:
  port: 80
